import { printer } from "../../utils/imagepath";

export const SidebarData1 = [
  {
    tittle: "Main Menu",
    hasSubRoute: true,
    icon: "layout-grid",
    showSubRoute: false,
    subRoutes: [
      {
        tittle: "Dashboard",
        hasSubRoute: true,
        showSubRoute: true,
        subRoutes: [
          {
            tittle: "Admin Dashboard",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/index",
            subRoutes: [],
          },
          {
            tittle: "Admin Dashboard 2",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/admin-dashboard",
            subRoutes: [],
          },
          {
            tittle: "Sales Dashboard",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/sales-dashboard",
            subRoutes: [],
          },
          {
            tittle: "Analytics Dashboard",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/analytics-dashboard",
            subRoutes: [],
          },
        ],
      },
      {
        tittle: "Super Admin",
        hasSubRoute: true,
        showSubRoute: true,
        subRoutes: [
          {
            tittle: "Dashboard",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/dashboard",
            subRoutes: [],
          },
          {
            tittle: "Companies",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/companies",
            subRoutes: [],
          },
          {
            tittle: "Subscriptions",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/subscription",
            subRoutes: [],
          },
          {
            tittle: "Packages",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/packages",
            subRoutes: [],
          },
          {
            tittle: "Domain",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/domain",
            subRoutes: [],
          },
          {
            tittle: "Purchase Transaction",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/purchase-transaction",
            subRoutes: [],
          },
        ],
      },
      {
        tittle: "Application",
        hasSubRoute: true,
        showSubRoute: true,
        base: "application",
        subRoutes: [
          {
            tittle: "Chat",
            route: "/chat",
            hasSubRoute: false,
            showSubRoute: false,
            customSubmenuTwo: false,
            subRoutes: [],
          },
          {
            tittle: "Call",
            hasSubRoute: true,
            showSubRoute: true,
            base: "application",
            subRoutes: [
              {
                tittle: "Video Call",
                route: "/video-call",
                hasSubRoute: false,
                showSubRoute: false,
                subRoutes: [],
              },
              {
                tittle: "Audio Call",
                route: "/audio-call",
                hasSubRoute: false,
                showSubRoute: false,
                subRoutes: [],
              },
              {
                tittle: "Call History",
                route: "/call-history",
                hasSubRoute: false,
                showSubRoute: false,
                subRoutes: [],
              },
            ],
          },
          {
            tittle: "Calendar",
            route: "/calendar",
            hasSubRoute: false,
            showSubRoute: false,
            customSubmenuTwo: false,
            subRoutes: [],
          },
          {
            tittle: "Email",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/email",
            customSubmenuTwo: false,
            subRoutes: [],
          },
          {
            tittle: "To Do",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/todo",
            customSubmenuTwo: false,
            subRoutes: [],
          },
          {
            tittle: "Notes",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/notes",
            customSubmenuTwo: false,
            subRoutes: [],
          },
          {
            tittle: "File Manager",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/file-manager",
            customSubmenuTwo: false,
            subRoutes: [],
          },
          {
            tittle: "Projects",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/projects",
            customSubmenuTwo: false,
            subRoutes: [],
          },
          {
            tittle: "Ecommerce",
            hasSubRoute: true,
            showSubRoute: true,
            subRoutes: [
              {
                tittle: "Products",
                hasSubRoute: false,
                showSubRoute: false,
                route: "/products",
                subRoutes: [],
              },
              {
                tittle: "Orders",
                hasSubRoute: false,
                showSubRoute: false,
                route: "/orders",
                subRoutes: [],
              },
              {
                tittle: "Customers",
                hasSubRoute: false,
                showSubRoute: false,
                route: "/customers",
                subRoutes: [],
              },
              {
                tittle: "Cart",
                hasSubRoute: false,
                showSubRoute: false,
                route: "/cart",
                subRoutes: [],
              },
              {
                tittle: "Checkout",
                hasSubRoute: false,
                showSubRoute: false,
                route: "/checkout",
                subRoutes: [],
              },
              {
                tittle: "Wishlist",
                hasSubRoute: false,
                showSubRoute: false,
                route: "/wishlist",
                subRoutes: [],
              },
              {
                tittle: "Reviews",
                hasSubRoute: false,
                showSubRoute: false,
                route: "/reviews",
                subRoutes: [],
              },
            ],
          },
          {
            tittle: "Social Feed",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/social-feed",
            subRoutes: [],
          },
          {
            tittle: "Search List",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/search-list",
            subRoutes: [],
          },
        ],
      },
      {
        tittle: "Layouts",
        hasSubRoute: true,
        icon: "layout-sidebar-right-collapse",
        showSubRoute: false,
        subRoutes: [
          {
            tittle: "Horizontal",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/layout-horizontal",
            subRoutes: [],
          },
          {
            tittle: "Detached",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/layout-detached",
            subRoutes: [],
          },
          {
            tittle: "Two Column",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/layout-two-column",
            subRoutes: [],
          },
          {
            tittle: "Hovered",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/layout-hovered",
            subRoutes: [],
          },
          {
            tittle: "Boxed",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/layout-boxed",
            subRoutes: [],
          },
          {
            tittle: "RTL",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/layout-rtl",
            subRoutes: [],
          },
          {
            tittle: "Dark",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/layout-dark",
            subRoutes: [],
          },
        ],
      },
    ],
  },

  {
    tittle: "Inventory",
    hasSubRoute: true,
    icon: "brand-unity",
    showSubRoute: false,
    activeRoute: "product",
    subRoutes: [
      {
        tittle: "Products",
        hasSubRoute: false,
        showSubRoute: true,
        route: "/product-list",
        subRoutes: [],
      },
      {
        tittle: "Create Product",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/add-product",
        subRoutes: [],
      },
      {
        tittle: "Expired Products",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/expired-products",
        subRoutes: [],
      },
      {
        tittle: "Low Stocks",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/low-stocks",
        subRoutes: [],
      },
      {
        tittle: "Category",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/category-list",
        subRoutes: [],
      },
      {
        tittle: "Sub Category",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/sub-categories",
        subRoutes: [],
      },
      {
        tittle: "Brands",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/brand-list",
        subRoutes: [],
      },
      {
        tittle: "Units",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/units",
        subRoutes: [],
      },
      {
        tittle: "Variant Attributes",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/variant-attributes",
        subRoutes: [],
      },
      {
        tittle: "Warranties",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/warranty",
        subRoutes: [],
      },
    ],
  },

  {
    tittle: "Sales & Purchase",
    hasSubRoute: true,
    icon: "layout-grid",
    showSubRoute: false,
    activeRoute: "users",
    subRoutes: [
      {
        tittle: "Stock",
        hasSubRoute: true,
        showSubRoute: false,
        subRoutes: [
          {
            tittle: "Manage Stock",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/manage-stocks",
            subRoutes: [],
          },
          {
            tittle: "Stock Adjustment",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/stock-adjustment",
            subRoutes: [],
          },
          {
            tittle: "Stock Transfer",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/stock-transfer",
            subRoutes: [],
          },
        ],
      },
      {
        tittle: "Sales",
        hasSubRoute: true,
        showSubRoute: false,
        route: "/sales-list",
        subRoutes: [
          {
            tittle: "Sales",
            hasSubRoute: true,
            showSubRoute: true,
            subRoutes: [
              {
                tittle: "Online Orders",
                hasSubRoute: false,
                showSubRoute: false,
                route: "/online-orders",
                subRoutes: [],
              },
              {
                tittle: "POS Orders",
                hasSubRoute: false,
                showSubRoute: false,
                route: "/pos-orders",
                subRoutes: [],
              },
            ],
          },
          {
            tittle: "Invoice",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/sales/invoices",
            subRoutes: [],
          },
          {
            tittle: "Sales Return",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/sales-returns",
            subRoutes: [],
          },
          {
            tittle: "Quotation",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/quotation-list",
            subRoutes: [],
          },
          {
            tittle: "POS",
            hasSubRoute: true,
            showSubRoute: true,
            route: "/pos",
            subRoutes: [
              {
                tittle: "POS 1",
                hasSubRoute: false,
                showSubRoute: false,
                route: "/pos",
                subRoutes: [],
              },
              {
                tittle: "POS 2",
                hasSubRoute: false,
                showSubRoute: false,
                route: "/pos-2",
                subRoutes: [],
              },
              {
                tittle: "POS 3",
                hasSubRoute: false,
                showSubRoute: false,
                route: "/pos-3",
                subRoutes: [],
              },
              {
                tittle: "POS 4",
                hasSubRoute: false,
                showSubRoute: false,
                route: "/pos-4",
                subRoutes: [],
              },
              {
                tittle: "POS 5",
                hasSubRoute: false,
                showSubRoute: false,
                route: "/pos-5",
                subRoutes: [],
              },
            ],
          },
        ],
      },
      {
        tittle: "Promo",
        hasSubRoute: true,
        showSubRoute: false,
        activeRoute: "promo",
        subRoutes: [
          {
            tittle: "Coupons",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/coupons",
            subRoutes: [],
          },
          {
            tittle: "Gift Cards",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/gift-cards",
            subRoutes: [],
          },
          {
            tittle: "Discount",
            hasSubRoute: true,
            showSubRoute: true,
            subRoutes: [
              {
                tittle: "Discount Plan",
                hasSubRoute: false,
                showSubRoute: false,
                route: "/discount-plan",
                subRoutes: [],
              },
              {
                tittle: "Discount",
                hasSubRoute: false,
                showSubRoute: false,
                route: "/discount",
                subRoutes: [],
              },
            ],
          },
        ],
      },
      {
        tittle: "Purchases",
        hasSubRoute: true,
        showSubRoute: false,
        activeRoute: "users",
        subRoutes: [
          {
            tittle: "Purchases",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/purchase-list",
            subRoutes: [],
          },
          {
            tittle: "Purchase Order",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/purchase-order-report",
            subRoutes: [],
          },
          {
            tittle: "Purchase Return",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/purchase-returns",
            subRoutes: [],
          },
        ],
      },
        {
    title: "Finance & Accounts",
    showAsTab: false,
    separateRoute: false,
    menu: [
      {
        menuValue: "Expenses",
        hasSubRoute: true,
        showSubRoute: true,
        icon: "file-text",
        subRoutes: [
          {
            menuValue: "Expenses",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/expenses",
          },
          {
            menuValue: "Expense Category",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/expense-category",
          },
        ],
      },
    ],
  },
      
      {
        tittle: "Income",
        hasSubRoute: true,
        showSubRoute: false,
        route: "/purchase-returns",
        subRoutes: [
          {
            tittle: "Income",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/income",
            subRoutes: [],
          },
          {
            tittle: "Income Category",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/income-category",
            subRoutes: [],
          },
        ],
      },
      {
        tittle: "Bank Accounts",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/account-list",
        subRoutes: [],
      },
      {
        tittle: "Money Transfer",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/money-transfer",
        subRoutes: [],
      },
      {
        tittle: "Balance Sheet",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/balance-sheet",
        subRoutes: [],
      },
      {
        tittle: "Trial Balance",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/trial-balance",
        subRoutes: [],
      },
      {
        tittle: "Cash Flow",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/cash-flow",
        subRoutes: [],
      },
      {
        tittle: "Account Statement",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/account-statement",
        subRoutes: [],
      },
    ],
  },
  {
    tittle: "UI Interface",
    hasSubRoute: true,
    icon: "users-group",
    showSubRoute: false,
    activeRoute: "users",
    subRoutes: [
      {
        tittle: "Base UI",
        hasSubRoute: true,
        icon: { printer },
        showSubRoute: false,
        activeRoute: "users",
        subRoutes: [
          {
            tittle: "Alerts",
            route: "/ui-alerts",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Accordion",
            route: "/ui-accordion",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Avatar",
            route: "/ui-avatar",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Badges",
            route: "/ui-badges",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Border",
            route: "/ui-borders",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Buttons",
            route: "/ui-buttons",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Button Group",
            route: "/ui-buttons-group",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Breadcrumb",
            route: "/ui-breadcrumb",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Card",
            route: "/ui-cards",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Carousel",
            route: "/ui-carousel",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Colors",
            route: "/ui-colors",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Dropdowns",
            route: "/ui-dropdowns",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Grid",
            route: "/ui-grid",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Images",
            route: "/ui-images",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Lightbox",
            route: "/ui-lightbox",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Media",
            route: "/ui-media",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Modals",
            route: "/ui-modals",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Offcanvas",
            route: "/ui-offcanvas",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Pagination",
            route: "/ui-pagination",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Progress",
            route: "/ui-progress",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Placeholders",
            route: "/ui-placeholders",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Range Slider",
            route: "/ui-rangeslider",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Spinner",
            route: "/ui-spinner",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Tabs",
            route: "/ui-nav-tabs",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Toasts",
            route: "/ui-toasts",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Tooltips",
            route: "/ui-tooltips",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Typography",
            route: "/ui-typography",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Video",
            route: "/ui-video",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Sortable",
            route: "/ui-sortable",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Swiperjs",
            route: "/ui-swiperjs",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
        ],
      },
      {
        tittle: "Advanced UI",
        hasSubRoute: true,
        showSubRoute: false,
        activeRoute: "users",
        subRoutes: [
          {
            tittle: "Ribbon",
            route: "/ui-ribbon",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Clipboard",
            route: "/ui-clipboard",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Drag & Drop",
            route: "/ui-drag-drop",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Rating",
            route: "/ui-rating",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Text Editor",
            route: "/ui-text-editor",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Counter",
            route: "/ui-counter",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Scrollbar",
            route: "/ui-scrollbar",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Sticky Note",
            route: "/ui-stickynote",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Timeline",
            route: "/ui-timeline",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
        ],
      },
      {
        tittle: "Charts",
        hasSubRoute: true,
        showSubRoute: false,
        activeRoute: "users",
        subRoutes: [
          {
            tittle: "Apex Charts",
            route: "/chart-apex",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Chart Js",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/chart-js",
            subRoutes: [],
          },
        ],
      },
      {
        tittle: "Icons",
        hasSubRoute: true,
        showSubRoute: false,
        activeRoute: "users",
        subRoutes: [
          {
            tittle: "Fontawesome Icons",
            route: "/icon-fontawesome",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Feather Icons",
            route: "/icon-feather",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Ionic Icons",
            route: "/icon-ionic",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Material Icons",
            route: "/icon-material",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Pe7 Icons",
            route: "/icon-pe7",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Simpleline Icons",
            route: "/icon-simpleline",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Themify Icons",
            route: "/icon-themify",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Typicon Icons",
            route: "/icon-typicon",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Flag Icons",
            route: "/icon-flag",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Tabler Icons",
            route: "/icon-tabler",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Bootstrap Icons",
            route: "/icon-bootstrap",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            tittle: "Remix Icons",
            route: "/icon-remix",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
        ],
      },
      {
        tittle: "Forms",
        hasSubRoute: true,
        showSubRoute: false,
        activeRoute: "users",
        subRoutes: [
          {
            tittle: "Form Elements",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/form-basic-inputs",
            subRoutes: [],
          },
          {
            tittle: "Form Validation",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/form-validation",
            subRoutes: [],
          },
          {
            tittle: "Tables",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/data-tables",
            subRoutes: [],
          },
        ],
      },
    ],
  },
  {
    tittle: "Profile",
    hasSubRoute: true,
    icon: "user-circle",
    showSubRoute: false,
    subRoutes: [
      {
        tittle: "Profile",
        route: "/profile",
        hasSubRoute: false,
        showSubRoute: false,
        subRoutes: [],
      },
      {
        tittle: "Pricing",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/pricing",
        subRoutes: [],
      },
      {
        tittle: "FAQ",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/faq",
        subRoutes: [],
      },
    ],
  },
  {
    tittle: "Reports",
    hasSubRoute: true,
    icon: "chart-bar",
    showSubRoute: false,
    activeRoute: "users",
    subRoutes: [
      {
        tittle: "Sales Report",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/sales-report",
        subRoutes: [],
      },
      {
        tittle: "Purchase Report",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/purchase-report",
        subRoutes: [],
      },
      {
        tittle: "Inventory Report",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/inventory-report",
        subRoutes: [],
      },
      {
        tittle: "Expense Report",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/expense-report",
        subRoutes: [],
      },
    ],
  },
  {
    tittle: "Settings",
    hasSubRoute: true,
    icon: "settings",
    showSubRoute: false,
    activeRoute: "users",
    subRoutes: [
      {
        tittle: "General Settings",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/general-settings",
        subRoutes: [],
      },
      {
        tittle: "Currencies",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/currency-settings",
        subRoutes: [],
      },
      {
        tittle: "Logout",
        hasSubRoute: false,
        showSubRoute: false,
        route: "/signin",
        subRoutes: [],
      },
    ],
  },
  {
    tittle: "More",
    hasSubRoute: true,
    icon: "circle-plus",
    showSubRoute: false,
    activeRoute: "More",
    subRoutes: [
      {
        tittle: "People",
        hasSubRoute: true,
        showSubRoute: false,
        subRoutes: [
          {
            tittle: "Customers",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/customers",
            subRoutes: [],
          },
          {
            tittle: "Suppliers",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/suppliers",
            subRoutes: [],
          },
          {
            tittle: "Stores",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/store-list",
            subRoutes: [],
          },
          {
            tittle: "Warehouses",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/warehouse",
            subRoutes: [],
          },
        ],
      },
      {
        tittle: "User Management",
        hasSubRoute: true,
        showSubRoute: false,
        subRoutes: [
          {
            tittle: "Users",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/users",
            subRoutes: [],
          },
          {
            tittle: "Roles & Permissions",
            hasSubRoute: false,
            showSubRoute: false,
            route: "/roles-permissions",
            subRoutes: [],
          },
        ],
      },
    ],
  },
];